# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:26:07+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class Result(BaseModel):
    message: Optional[str] = None
    permalink: Optional[str] = None


class SearchRequest(BaseModel):
    query: str = Field(..., description='Search query')
